[project]
name = "poetry-plugin-migrate"
version = "0.2.0"
description = "Poetry plugin to migrate pyproject.toml from Poetry v1 to v2 (PEP-621 compliant)"
license = "MIT"
authors = [{ name = "zyf722", email = "MaxMixAlex@protonmail.com" }]
keywords = ["poetry", "migrate", "PEP-621", "pyproject.toml"]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "packaging (>=24.2)",
    "poetry (>=2.2.1,<3.0.0)",
]
dynamic = ["classifiers"]

[project.urls]
homepage = "https://github.com/zyf722/poetry-plugin-migrate"
repository = "https://github.com/zyf722/poetry-plugin-migrate"

[project.entry-points."poetry.application.plugin"]
poetry-plugin-migrate = "poetry_plugin_migrate.plugin:MigrateApplicationPlugin"

[tool.poetry]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]
requires-poetry = ">=2.2.1"

[dependency-groups]
dev = [
    "ruff (>=0.15.7,<0.16.0)",
    "mypy (>=1.19.0,<2.0.0)",
    "poethepoet (>=0.42.1,<0.43.0)",
    "python-semantic-release (>=9.17.0,<10.0.0)"
]
test = [
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-mock (>=3.14.0,<4.0.0)",
    "pytest-cov (>=6.0.0,<7.0.0)"
]

[tool.mypy]
python_version = "3.10"
strict = true
disallow_any_explicit = true
warn_unused_ignores = true
show_error_codes = true

[tool.ruff]
output-format = "grouped"

[tool.ruff.lint]
extend-select = [
    "I",
    "UP",
    "A",
    "N",
    "SIM",
    "RET",
    "PTH",
    "C4",
    "B",
    "RUF",
    "FAST",
]
ignore = ["B008", "E501", "UP045", "UP046", "SIM117", "RET504", "RUF001", "RUF002", "RUF003", "A002"]

[tool.poe.tasks]
lint-check = "ruff check ."
format-check = "ruff format --check ."
type-check = "mypy ."
test = "pytest -q -p no:cacheprovider"
static-check.sequence = [
    "lint-check",
    "format-check",
    "type-check"
]
static-check.ignore_fail = "return_non_zero"
check.sequence = ["static-check", "test"]
check.ignore_fail = "return_non_zero"

[tool.coverage.run]
branch = true

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version"
]
branch = "main"
tag_format = "{version}"
commit_author = "github-actions[bot] <actions@github.com>"
commit_message = "chore(release): v{version}"

[tool.semantic_release.changelog]
keep_trailing_newline = true

[tool.semantic_release.remote]
type = "github"
token = { env = "GH_TOKEN" }

[tool.semantic_release.publish]
upload_to_vcs_release = true

[build-system]
requires = ["poetry-core (>=2.0.0,<3.0.0)"]
build-backend = "poetry.core.masonry.api"
